SELECT A.CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM BOOK A
RIGHT OUTER JOIN BOOK_SALES B ON B.BOOK_ID = A.BOOK_ID
WHERE TO_CHAR(B.SALES_DATE, 'YYYYMM') = '202201'
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY